[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Taylor Daniels", email = "tdan1101@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "requests>=2.34.2",
    "starlette>=1.6.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
